# Generated by Django 4.1.6 on 2023-02-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('upload_img', models.ImageField(blank=True, upload_to='image/%Y/%m/%d/')),
                ('upload', models.FileField(upload_to='video/%Y/%m/%d/')),
                ('descr', models.TextField()),
                ('site_url', models.URLField()),
                ('git_url', models.URLField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
