# Generated by Django 4.1.6 on 2023-02-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPortfolioApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliostructure',
            name='upload_img',
            field=models.ImageField(blank=True, upload_to='image/%Y/%m/%d/'),
        ),
    ]
