# Generated by Django 4.1.6 on 2023-02-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPortfolioApp', '0002_alter_portfoliostructure_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliostructure',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
