# Generated by Django 4.1.6 on 2023-02-14 16:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WebPortfolioApp', '0003_alter_portfoliostructure_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliostructure',
            name='likes',
            field=models.ManyToManyField(related_name='proj_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
