# Generated by Django 4.1.6 on 2023-03-03 15:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WebPortfolioApp', '0007_alter_portfoliostructure_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliostructure',
            name='likes',
            field=models.ManyToManyField(related_name='project_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
