# Generated by Django 4.1.6 on 2023-03-04 13:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WebPortfolioApp', '0009_remove_portfoliostructure_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliostructure',
            name='liked',
        ),
        migrations.AddField(
            model_name='portfoliostructure',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
