# Generated by Django 4.1.6 on 2023-03-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPortfolioApp', '0012_comment_commentator'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliostructure',
            name='descr_en_us',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='portfoliostructure',
            name='descr_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='portfoliostructure',
            name='title_en_us',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='portfoliostructure',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
